# Generated by Django 6.1 on 2026-08-12 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='N/A', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('serial_number', models.CharField(verbose_name=100)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField()),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged')], default='new', max_length=40)),
                ('status', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('asset_description', models.TextField(blank=True, default='N/A', null=True)),
                ('image', models.ImageField(upload_to='assets_image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.category')),
            ],
        ),
    ]
