# Generated by Django 6.1 on 2026-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
