# Generated by Django 6.1 on 2026-08-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_asset_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_price',
            field=models.IntegerField(),
        ),
    ]
