# Generated by Django 6.1 on 2026-08-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_asset_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assetId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
