# Generated by Django 6.1 on 2026-09-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_asset_assetid_alter_asset_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
