# Generated by Django 6.1 on 2026-08-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('person_email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('it', 'IT'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('administration', 'Administration'), ('accounts', 'Accounts'), ('customer_support', 'Customer Support')], default='it', max_length=50)),
                ('person_designation', models.CharField(max_length=200)),
                ('assignment_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
