# Generated by Django 6.1 on 2026-08-22 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignTo',
            new_name='ToAssign',
        ),
    ]
