# Generated by Django 6.1 on 2026-08-25 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_asset_assetid_alter_asset_quantity'),
        ('user', '0002_rename_assignto_toassign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toassign',
            name='person_designation',
        ),
        migrations.RemoveField(
            model_name='toassign',
            name='person_email',
        ),
        migrations.RemoveField(
            model_name='toassign',
            name='person_name',
        ),
        migrations.AddField(
            model_name='toassign',
            name='assets',
            field=models.ManyToManyField(to='manager.asset'),
        ),
        migrations.AddField(
            model_name='toassign',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toassign',
            name='assignee_name',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='toassign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='toassign',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='toassign',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
