# Generated by Django 6.1 on 2026-08-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_toassign_person_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toassign',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
