# Generated by Django 6.1 on 2026-09-02 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_toassign_return_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returning', models.CharField(choices=[('returned', 'Returned'), ('maintenance', 'Maintenance')], default='returned')),
                ('assigned_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.toassign')),
            ],
        ),
    ]
