# Generated by Django 6.1 on 2026-09-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_assetreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetreturn',
            name='returning',
            field=models.CharField(choices=[('returned', 'Returned'), ('maintenance', 'Maintenance')], default='returned', max_length=30),
        ),
    ]
