# Generated by Django 6.1 on 2026-09-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_assetreturn_returning'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetreturn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
